spring:
  application:
    name: class_blog_jpa_v1
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_demo?useSSL=false&serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  profiles:
    active: dev

server:
  port: 8080


